// RootLayout.tsx
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import styles from "./styles.module.css"
import Navbar from "@/components/Navbar/Navbar"
import { Header } from "@/components/Header/Header"

import Providers from "./providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <section className={styles.container}>
            <Navbar />

            <div className={styles.content}>{children}</div>
          </section>
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
